mpesa:
  daraja:
    myAddress: https://6eaf-105-160-113-226.ngrok.io
    consumer-key: kAg5pZcWJVfuFihVaSIXNwN170IeBIYY
    consumer-secret: ELLQw8YWcnvnwYVj
    grant-type: client_credentials
    oauth-endpoint: https://sandbox.safaricom.co.ke/oauth/v1/generate
    stkPassKey: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
    shortCode: 174379
    stk-endpoint: https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
    stkCallbackUrl: https://6eaf-105-160-113-226.ngrok.io/mobile-money/stk
    stkStatusCheckUrl : https://sandbox.safaricom.co.ke/mpesa/stkpushquery/v1/query